version: No.{build}

branches:
  only:
    - xmake

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64
  - x86

install:
  - ps: Invoke-WebRequest "https://github.com/tboox/xmake/releases/download/v2.1.3/xmake-v2.1.3.exe" -OutFile "xmake-installer.exe"
  - cmd: xmake-installer.exe /S /D=C:\xmake
  - cmd: PATH=%PATH%;C:\xmake

before_build:
  - cd src
  - if %platform%==x64 xmake f -a x64

build_script:
  - xmake -v
